title: LibreHEMS
description: Your goto resource for all things Home Energy Management
theme: just-the-docs

url: https://librehems.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
